### ISSUE TITLE
Unable to generate proof with ts/js

### ISSUE THREAD

**Issue by manylov** [aragonzkresearch/noir-trie-proofs#29]
I've created repo, reproducing the issue.

https://github.com/manylov/noir-trie-proofs-js-issue

it is a simple storage proof, verifying evm storage value.

nargo prove/verify works good.

but when i try to do await backends.main.generateProof(witness); in ts

i got error

```
Error [RuntimeError]: unreachable
    at wasm://wasm/01fd9442:wasm-function[17622]:0x78a386
    at wasm://wasm/01fd9442:wasm-function[223]:0x31f23
    at wasm://wasm/01fd9442:wasm-function[218]:0x31dac
    at wasm://wasm/01fd9442:wasm-function[181]:0x31048
    at BarretenbergWasmMain.call (/Users/maksimmanylov/dev/noir/noir-trie-proofs-js-issue/node_modules/@aztec/bb.js/src/barretenberg_wasm/barretenberg_wasm_base/index.ts:101:34)
    at BarretenbergWasmMain.callWasmExport (/Users/maksimmanylov/dev/noir/noir-trie-proofs-js-issue/node_modules/@aztec/bb.js/src/barretenberg_wasm/barretenberg_wasm_main/index.ts:109:10)
    at callback (/Users/maksimmanylov/dev/noir/noir-trie-proofs-js-issue/node_modules/comlink/src/comlink.ts:329:36)
    at MessagePort.l (/Users/maksimmanylov/dev/noir/noir-trie-proofs-js-issue/node_modules/@aztec/bb.js/src/barretenberg_wasm/helpers/node/node_endpoint.ts:12:11)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:814:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)
```

note: i've tried ./issue/storage-inputs.ts as numbers values, and as hexified ones - with the same error.

**Comment by LogvinovLeon** [comment]
Please run `nargo info`. The most probable cause is that your circuit has more than 500k (2^19) constraints and therefore wasm prover can not be used
